# my global config
global:
  scrape_interval:     30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'ymir-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "nodeexporter"
    static_configs:
    - targets: ["nodeexporter:9100"]

  - job_name: "cadvisor"
    static_configs:
    - targets: ["cadvisor:8080"]

  - job_name: "ymir-backend"
    static_configs:
    - targets: ["backend:80", "backend:9527"]

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://web:80/health # YMIR-web
        - http://backend:80/health # YMIR-backend App.
        - http://backend:9527/health # YMIR-backend Viewer.
        - http://baidu.com # Network check.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox:9115"
