version: "3.1"
services:
  label_nginx:
    image: labelfree/open_frontend:latest
    env_file:
      - .env
    ports:
      - ${LABEL_TOOL_HOST_PORT}:80
    networks:
      - labelfreenetwork
    restart: always

  label_api:
    image: labelfree/open:latest
    command: gunicorn --conf /code/config/gunicorn.py  --log-config /code/config/logging.conf --chdir /code/labelfree app:app
    env_file:
      - .env
    volumes:
      - ${BACKEND_SANDBOX_ROOT}:${BACKEND_SANDBOX_ROOT}
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@label_mysql:3306/labelfree
      REDIS_HOST: label_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      S3_ENDPOINT_URL: ${LABEL_TOOL_HOST_IP}:${LABEL_TOOL_S3_PORT}
      S3_SECRET_ACCESS_KEY: ${MYSQL_ROOT_PASSWORD}
      FLASK_APP: labelfree.app
      LABEL_ENV: dev
      LABEL_BUILD: pro
    networks:
      - labelfreenetwork
    restart: always

  label_celery_worker:
    image: labelfree/open:latest
    command: celery -A labelfree.app.celery worker -l info 
    env_file:
      - .env
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@label_mysql:3306/labelfree
      REDIS_HOST: label_redis
      REDIS_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      S3_ENDPOINT_URL: ${LABEL_TOOL_HOST_IP}:${LABEL_TOOL_S3_PORT}
      S3_SECRET_ACCESS_KEY: ${MYSQL_ROOT_PASSWORD}
      FLASK_APP: labelfree.app
      LABEL_ENV: dev
    networks:
      - labelfreenetwork
    restart: always

  label_mysql:
    image: mysql:5.7.22
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: labelfree
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - ${YMIR_PATH}/labelfree/mysql_data:/var/lib/mysql
    networks:
      - labelfreenetwork
    restart: always

  label_redis:
    image: bitnami/redis:5.0.4
    environment:
      REDIS_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - labelfreenetwork
    restart: always

  label_minio:
    image: quay.io/minio/minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MINIO_ROOT_USER: labelfree
    command: server /data --console-address ":9001"
    ports:
      - ${LABEL_TOOL_S3_PORT}:9000
    volumes:
      - ${YMIR_PATH}/labelfree/minio_data:/data
    networks:
      - labelfreenetwork

    restart: always

networks:
  labelfreenetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.68.254.0/24
          gateway: 172.68.254.1
