version: "3.3"
services:
  label-nginx:
    image: labelfree/open_frontend:3.3.1
    env_file:
      - .env
    ports:
      - ${LABEL_TOOL_HOST_PORT}:80
    networks:
      - ymirnetwork
    restart: always

  label_api:
    image: labelfree/open:3.3.1
    command: gunicorn --conf /code/config/gunicorn.py  --log-config /code/config/logging.conf --chdir /code/labelfree app:app
    env_file:
      - .env
    volumes:
      - ${BACKEND_SANDBOX_ROOT}:${BACKEND_SANDBOX_ROOT}
      - ${YMIR_PATH}/labelfree/backend_log:/var/log/gunicorn
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@label_mysql:3306/labelfree
      REDIS_HOST: label_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      S3_ENDPOINT_URL: http://label-minio:9000
      S3_SECRET_ACCESS_KEY: ${MYSQL_ROOT_PASSWORD}
      FLASK_APP: labelfree.app
      LABEL_ENV: dev
      LABEL_BUILD: pro
    networks:
      - ymirnetwork
    restart: always

  label_seg:
    image: labelfree/open_seg:3.3.1
    command: gunicorn --conf /code/config/gunicorn.py  --log-config /code/config/logging.conf --chdir /code/segmentation app:app
    runtime: runc
    volumes:
      - ${YMIR_PATH}/labelfree/seg_log:/var/log/gunicorn
    environment:
      FLASK_APP: labelfree.app
      SEG_DEBUG: "false"
      NVIDIA_VISIBLE_DEVICES: all
      FLAGS_fast_eager_deletion_mode: "true"
      FLAGS_eager_delete_tensor_gb: 0.0
      FLAGS_memory_fraction_of_eager_deletion: 1
      G_MAX_REQUESTS: 100
      G_MAX_REQUESTS_JITTER: 10
      SERVER_RUNTIME: "runc"
    networks:
      - ymirnetwork
    restart: always

  label_celery_worker:
    image: labelfree/open:3.3.1
    command: celery -A labelfree.app.celery worker -l info -c 4 -B
    env_file:
      - .env
    volumes:
      - ${BACKEND_SANDBOX_ROOT}:${BACKEND_SANDBOX_ROOT}
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@label_mysql:3306/labelfree
      REDIS_HOST: label_redis
      REDIS_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      S3_ENDPOINT_URL: http://label-minio:9000
      S3_SECRET_ACCESS_KEY: ${MYSQL_ROOT_PASSWORD}
      FLASK_APP: labelfree.app
      LABEL_ENV: dev
    networks:
      - ymirnetwork
    restart: always

  label_mysql:
    image: mysql:5.7.22
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: labelfree
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --max_connections=1000
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - ${YMIR_PATH}/labelfree/mysql_data:/var/lib/mysql
    networks:
      - ymirnetwork
    restart: always

  label_redis:
    image: redis:5.0.4
    command: redis-server --appendonly yes --requirepass ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${YMIR_PATH}/labelfree/redis-data:/data
    networks:
      - ymirnetwork
    restart: always

  label-minio:
    image: quay.io/minio/minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MINIO_ROOT_USER: labelfree
    command: server /data --console-address ":9001"
    volumes:
      - ${YMIR_PATH}/labelfree/minio_data:/data
    networks:
      - ymirnetwork

    restart: always

networks:
  ymirnetwork:
    name: ${COMPOSE_PROJECT_NAME}_ymirnetwork
    external: true
