info:
  contact: {}
paths:
  /api/v1/users/{userID}/repo/{repoID}/branch/{branchID}/assets:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Repo ID
        in: path
        name: repoID
        required: true
        type: string
      - description: Branch ID
        in: path
        name: branchID
        required: true
        type: string
      - description: Offset, default is 0
        in: query
        name: offset
        type: string
      - description: limit, default is 1
        in: query
        name: limit
        type: string
      - description: e.g. class_ids=1,3,7
        in: query
        name: class_ids
        type: string
      - description: e.g. annotation_types=GT,PRED
        in: query
        name: annotation_types
        type: string
      - description: e.g. current_asset_id=xxxyyyzzz
        in: query
        name: current_asset_id
        type: string
      - description: e.g. cm_types=0,1,2,3 NotSet=0,TP=1,FP=2,FN=3,TN=4,Unknown=5,MTP=11,IGNORED=12
        in: query
        name: cm_types
        type: string
      - description: ck pairs, e.g. cks=xxx,xxx:,xxx:yyy, e.g. camera_id:1
        in: query
        name: cks
        type: string
      - description: tag pairs, e.g. cks=xxx,xxx:,xxx:yyy, e.g. camera_id:1
        in: query
        name: tags
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '''code'': 0, ''msg'': ''Success'', ''Success'': true, ''result'':
            constants.QueryAssetsResult'
          schema:
            type: string
      summary: Query single or set of assets.
  /api/v1/users/{userID}/repo/{repoID}/branch/{branchID}/dataset_meta_count:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Repo ID
        in: path
        name: repoID
        required: true
        type: string
      - description: Branch ID
        in: path
        name: branchID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '''code'': 0, ''msg'': ''Success'', ''Success'': true, ''result'':
            constants.QueryDatasetStatsResult'
          schema:
            type: string
      summary: Query dataset info, lightweight api.
  /api/v1/users/{userID}/repo/{repoID}/branch/{branchID}/dataset_stats:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Repo ID
        in: path
        name: repoID
        required: true
        type: string
      - description: Branch ID
        in: path
        name: branchID
        required: true
        type: string
      - description: e.g. class_ids=1,3,7
        in: query
        name: class_ids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '''code'': 0, ''msg'': ''Success'', ''Success'': true, ''result'':
            constants.QueryDatasetStatsResult'
          schema:
            type: string
      summary: Query dataset Stats.
  /api/v1/users/{userID}/repo/{repoID}/branch/{branchID}/model_info:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Repo ID
        in: path
        name: repoID
        required: true
        type: string
      - description: Branch ID
        in: path
        name: branchID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '''code'': 0, ''msg'': ''Success'', ''Success'': true, ''result'':  constants.MirdataModel'
          schema:
            type: string
      summary: Query model info.
  /api/v1/users/{userID}/repo/{repoID}/dataset_duplication:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Repo ID
        in: path
        name: repoID
        required: true
        type: string
      - description: e.g. candidate_dataset_ids=xxx,yyy
        in: query
        name: candidate_dataset_ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '''code'': 0, ''msg'': ''Success'', ''Success'': true, ''result'':
            ''duplication: 50, total_count: {xxx: 100, yyy: 200}'''
          schema:
            type: string
      summary: Query dataset dups.
swagger: "2.0"
