# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: backend-unittest

on:
  pull_request:
    branches:
      - master
      - dev
      - prerelease

env:
  PYTHONPATH: ./ymir/backend
  FIRST_ADMIN: admin@example.com
  FIRST_ADMIN_PASSWORD: fake_passwd

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        time pip install tox
      working-directory: ymir/backend
    - name: Cache Tox Environment
      uses: actions/cache@v3
      with:
        path: |
          ymir/backend/.tox
          ymir/backend/.mypy_cache
        # requirements.txt and requirements-dev.txt have versioning info that would
        # impact the tox environment.
        key: tox-${{ hashFiles('ymir/backend/requirements.txt', 'ymir/backend/requirements-dev.txt') }}
    - name: Test with tox
      run: |
        git config --global user.name 'CI-test'
        git config --global user.email 'deployer@ymir-team'
        tox
      working-directory: ymir/backend
