# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: uniitest

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'docker_executor/sample_executor/**'

jobs:
  executor-framework-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r executor/requirements.txt
        pip install -r executor/requirements-ci.txt
      working-directory: docker_executor/sample_executor
    - name: mypy
      run: |
        mypy .
      working-directory: docker_executor/sample_executor/executor
    - name: flake8
      run: |
        flake8 .
      working-directory: docker_executor/sample_executor/executor
    - name: Test with pytest
      run: |
        python tests/__main__.py
      working-directory: docker_executor/sample_executor
